currency:
  available:
    - "RUB"
cost:
  rub:
    perKg: 400
    minimalPricePerKg: 350
    perMetre: 1000
    minimalPricePerMetre: 350

coordinates:
  distance:
    min: 450_000 # metres
  latitude:
    min: 45
    max: 65
  longitude:
    min: 30
    max: 96
